# Email address registered on the noip account, e.g. "email@example.com"
USERNAME="${EMAIL}"

# Password of the noip account
PASSWORD="$PASSWORD"

# Your hostname, group name, or a comma-delimited list of a mix of them, e.g. "example.ddns.net".
DOMAINS="${DOMAINS}"

# Examples: 5 m, 5 h, 5 d. Minimum is 5 minutes.
INTERVAL='30m'
